# Python Course - Chapter 5 : Arrays and the numpy library

## 1) Discovering the numpy library

The `numpy` library is used to represent vectors and matrix in Python. It is mostly used for linear algebra but before anything, it is a way better way to represent lists of numbers and allows to do operations on these 'lists' (which are actually converted to arrays, a type specific to the numpy library). It is also used to represent lists of lists as matrix which are two-dimensional arrays.<br>
<br>
When importing the `numpy` library, its name is usually shortened to `np` :

In [2]:
import numpy as np

We can then call the functions of the `numpy` library using the syntax `np.function_name`, as usual.<br>
In order to convert a list to an array, we can use the function `np.array` :

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
print(np.shape(a))

(3, 4)


Here, we created a matrix of `int` objects, of size $3 \times 4$, using the `np.array` function. If we want to create a list of `float` objects instead, we can avoid any ambiguity by precising the type of the array using the optional parameter `dtype` (data type) in the `np.array` function :

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype = float)
print(a)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


## 2) Matrix calculation