# Introduction to numpy

## Correction

Before beginning the exercises, import the numpy library.

In [3]:
import numpy as np

### Exercise 1 - Create a ndarray list

1. Create the ndarray list [2, 7, 5, 6].
2. Create the ndarray list with all the numbers from 1 to 100. 
3. Create the ndarray list containing 101 elements, 0 being the lowest and 20 the highest. 
4. Create the ndarray list with all the numbers from 1 to 50, but only those that can be divided by 3. 

In [4]:
a = np.array([2, 7, 5, 6])
b = np.arange(1, 101)
c = np.linspace(0, 20, 101)
d = np.arange(1, 50, 3)

print(a)
print(b)
print(c)
print(d)

[2 7 5 6]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.
 11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8
 14.  14.2 14.4 14.6 14.8 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6
 16.8 17.  17.2 17.4 17.6 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4
 19.6 19.8 20. ]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


### Exercise 2 - Create a ndarray matrix

1. Create a matrix with 4 rows and 2 columns with only 0. 
2. Create a matrix with 2 rows and 2 columns, with only 1. 
3. Create a matrix with 4 rows and 25 colums, with all the numbers from 1 to 100. 
4. Print the shape of each matrix. 

In [5]:
A = np.zeros((4,2))
B = np.ones((2,2))
C = np.eye(3)
D = np.reshape(np.arange(1, 101), (4, 25))

print(A)
print(B)
print(C)
print(D)
print("Shape A :", A.shape)
print("Shape B :", B.shape)
print("Shape C :", C.shape)
print("Shape D :", D.shape)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25]
 [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43
   44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94  95  96  97  98  99 100]]
Shape A : (4, 2)
Shape B : (2, 2)
Shape C : (3, 3)
Shape D : (4, 25)


### Exercise 3 - Operations with ndarray lists

The goal of this exercise is to understand the differences between operations made with regular lists and operations made with numpy lists. 

1. Create the regular list (not numpy) `reg1` of length 5, with all 1, and the list `reg2` of length 5, with coefficients from 1 to 5. 
2. Create the lists `nump1` and `nump2`, which are the same as `reg1` and `reg2`, but that are numpy lists. 
3. Try to sum `reg1` and `reg2` on one side, and `nump1` and `nump2` on the other side. What do you observe ? How could you do to sum correctly `reg1` and `reg2` ? 
4. Try to multiply by coefficient `reg1` and `reg2` on one side, and `nump1` and `nump2` on the other side. What do you observe ? How could you do to multiply correctly `nump1` and `nump2` ? 

In [ ]:
reg1 = [1, 1, 1, 1, 1]
reg2 = [1, 2, 3, 4, 5]
nump1 = np.array(reg1)
nump2 = np.array(reg2)

In [21]:
print("concatenation: ", reg1+reg2)
print("numpy sum: ", nump1+nump2)
sum = [reg1[i]+reg2[i] for i in range(5)]
print("regular sum: ", sum)

concatenation:  [1, 1, 1, 1, 1, 1, 2, 3, 4, 5]
numpy sum:  [2 3 4 5 6]
regular sum:  [2, 3, 4, 5, 6]


In [20]:
# print(reg1*reg2) the operation doesn't work because it's not vectorial
print("numpy multiplication: ", nump1*nump2)
mul = [reg1[i]*reg2[i] for i in range(5)]
print("regular multiplication: ", mul)

numpy multiplication:  [1 2 3 4 5]
regular multiplication:  [1, 2, 3, 4, 5]


### Exercise 4

1. Create a matrix M 3X3 with only 1 on the diagonals and 0 for the rest. 
2. Create a matrix N 3X3 with coefficients from 1 to 9. 
3. Create the matrix L, which is the multiplication by coefficient of M and N. 
4. Create the matrix S, which is the sum by coefficient of M and N. 
5. Create the matrix P, which is the transposition of the matrix M. 
6. Create the matrix O, which calculate the product of M and N. 

In [8]:
M = np.eye(3)
print("M", M)
N = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("N", N)
L = M*N
print("L", L)
S = M + N 
print("S", S)
P = M.T
print("P", P)
print("O", M@N)


M [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
N [[1 2 3]
 [4 5 6]
 [7 8 9]]
L [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
S [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
P [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
O [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Exercise 5 - Product of matrixes [Difficult]

Given two Numpy arrays (matrices), write a function to compute the product of the two matrices of shape 2X2 (not the product coefficient by coefficient). As a reminder, for 2 matrices [[a, b], [c, d]] and [[e, f], [g, h]], the product of the matrices [[ae+bg, af+bh], [ce+dg, cf+dh]]. 
Test your function. 

In [23]:
def product(M, N):
    S = np.zeros((2,2))
    for i in range(2):
        for j in range(2):
            S[i, j] = M[i, 0]*N[0, j] + M[i, 1]*N[1, j]
    return S


print(product(np.array([[1, 2],[3, 4]]), np.array([[0, 1],[2, 3]])))

[[ 4.  7.]
 [ 8. 15.]]


### Exercise 6 - Plot a cosine wave

Create an array of 100 evenly spaced values between 0 and 2π, then compute the cosine of each value.
1. Create the x values using np.linspace and np.pi
2. Compute y = cos(x) using np.cos
3. Find the maximum, minimum, and mean of the resulting array

In [25]:
# 1. Create x values from 0 to 2π
x = np.linspace(0, 2 * np.pi, 100)
print("x", x)

# 2. Compute cosine
y = np.cos(x)
print("y", y)

# 3. Stats
print("Max:", np.max(y))   
print("Min:", np.min(y))      
print("Mean:", np.mean(y))    

x [0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.6485

### Exercise 7 - Quadratic function explorer

Given the quadratic function:
$f(x)=2x^2−3x−5$
Tasks:
1. Create an array x of 500 values between -3 and 5 using np.linspace
2. Compute f(x) for all values at once
3. Find the minimum value of f(x) and the x where it occurs
4. Verify the two roots are close to x = -1 and x = 2.5. find the x values in your array closest to each root

Hint : you can use `np.argmin(x)` to find the index of the minimum of the list. 

In [26]:
# 1. x values
x = np.linspace(-3, 5, 500)

# 2. Compute f(x)
f = 2*x**2 - 3*x - 5

# 3. Minimum of f(x)
min_val = np.min(f)
min_x   = x[np.argmin(f)]
print(f"Minimum: f({min_x:.3f}) = {min_val:.3f}")
# Minimum: f(0.751) = -6.125

# 4. Where is f(x) < 0?
below = x[f < 0]
print(f"f(x) < 0 from x = {below[0]:.3f} to x = {below[-1]:.3f}")
# f(x) < 0 from x = -1.000 to x = 2.500

# 5. Closest x to each root
for root in [-1.0, 2.5]:
    idx = np.argmin(np.abs(x - root))
    print(f"Near root {root}: f({x[idx]:.4f}) = {f[idx]:.4f}")
# Near root -1.0:  f(-1.0000) = 0.0000
# Near root  2.5:  f( 2.5000) = 0.0000

Minimum: f(0.752) = -6.125
f(x) < 0 from x = -0.996 to x = 2.499
Near root -1.0: f(-0.9960) = -0.0280
Near root 2.5: f(2.4990) = -0.0070
